apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wordpress-externalsecret
  namespace: wordpress
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secretstore-gcp-sm
  target:
    name: wordpress-secret
    creationPolicy: Owner
  data:
    - secretKey: wordpress-password
      remoteRef:
        key: wordpress-user-password-sm
        version: latest
    - secretKey: mariadb-password
      remoteRef:
        key: wordpress-db-password-sm
        version: latest
