apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secretstore-gcp-sm
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      projectID: PROJECT_ID
      auth:
        workloadIdentity:
          clusterLocation: asia-northeast1
          clusterName: my-gke
          clusterProjectID: PROJECT_ID
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
