apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-wide-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:melanmeg/my-cloudnative-entry.git
        revision: main
        directories:
          - path: k8s/apps/cluster-wide-apps/*
  template:
    metadata:
      # 各Application が argocd namespace に配置されるため prefix した方が安全
      name: "cluster-wide-apps-{{path.basenameNormalized}}"
      namespace: argocd
    spec:
      project: cluster-wide-apps
      source:
        repoURL: git@github.com:melanmeg/my-cloudnative-entry.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "cluster-wide-apps"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-wide-app-resources
  namespace: argocd
spec:
  project: argocd-root
  source:
    repoURL: git@github.com:melanmeg/my-cloudnative-entry.git
    targetRevision: main
    path: k8s/apps/cluster-wide-app-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: "cluster-wide-apps"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wordpress-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:melanmeg/my-cloudnative-entry.git
        revision: main
        directories:
          - path: k8s/apps/myapp/wordpress
  template:
    metadata:
      name: "{{path.basenameNormalized}}"
      namespace: argocd
    spec:
      project: wordpress
      source:
        repoURL: git@github.com:melanmeg/my-cloudnative-entry.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: wordpress
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
          - Replace=true
        retry:
          limit: -1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
