configs:
    cm:
        dex.config: ENC[AES256_GCM,data:GP0Cd30cKgZUrV6NxgXDS0wSZQwjkfQlQVeQwn1mcJsouDoTzCfX6OKYa+UbI5yvdqksnA0zg/Z1IX6tLmsX2Mey/PffiscrPpIG64vc2vYjzXTo0f7Tepq0CLrmu9IebZQLV0tp7JcrHBadn1elfUXXljNry7v6ElPGYX+xuAJ7lSdnNjsRIWudDkhDbHrDQvjiFUOg56GXqTpMOCkOctM4ZLjS0W6YqeHg,iv:7a+2rO9tPna7InAm6R6LujWc2kIWk46g+MZ8x4gJn9Y=,tag:PQ8piIjrzsB0mjWflJoFXw==,type:str]
    rbac:
        policy.csv: ENC[AES256_GCM,data:3w9Ye3q/a+3Ti4J9EEdAxwEwWKMDN3b3dPehNMDi0ZLdtXGp+RVE,iv:i8SLDBWU6BmcYl68Pw7HaWubl/9xFXiiCJckW88t2nE=,tag:gG5Vnlh/ClqOC+UsEv0rxw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/test-project-373118/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2024-11-18T06:47:43Z"
          enc: CiQAdOGM+jN572aFtFAB+Y3gJEYG3L0HVOG8Dzd3KTYx4eaNomQSSQBuGHVKESJkkoESYo6y1GTS/HOPv19gY94dTWlWsswOeuWBFudodhmPfKFx/XHAFnBdbbGYgkqVg2qHa34I7ClNJQBp+aFR1xU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-18T06:47:43Z"
    mac: ENC[AES256_GCM,data:mvH1MkDvLzdFU45kKwstEGLXfXucRkyvkjWuHNYMI7t9BBh40jaFLmSOTKVCR3/Uex7NltoBoNmw7/WvRrVKRcgsnbB/e3xKd7Q3xD9VfDuOlo/ZauCEDKWjLH6z3Z+K1gsLkrcCeKCYDXLvh5maFip3x3KGxJPSWmAqg2XFGqY=,iv:jOJJH8HGEB7e114g+2QoYM6zegZpwLvwi23tWrHZSy8=,tag:LeJ2sjkrTADPUXH8w7jtTw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
