#ENC[AES256_GCM,data:a/Fa9E8l+09cdVhlCRvlWBMcWho2LAOXEQw6vI2xof869aZGQQhh02FHKlH654qNzpunpvBaVj3lq8MfJ+JdutBwkADHMKSxJxCnO0JtD0QMdP01bc9khA==,iv:k1tbLSK3hGwyjwM2xQEVzjoZZysCfe46RRjGJqQ+p0c=,tag:VLXIJ8gMnAJ/RriqXpYiug==,type:comment]
apiVersion: ENC[AES256_GCM,data:SdI=,iv:83FNr1EgIB2dR2PWeS4yPcZWF4DLyC1X8fLvePaaTL0=,tag:hHerqlcBH3FlG9Sx0AE8ng==,type:str]
kind: ENC[AES256_GCM,data:cOXwgK5H,iv:BgwTSVRr9zKyQkHpNzql+Q4xv3t59IxbuZuI+lxCIMw=,tag:uq0D+vrrF3qwHbQxdOmCkw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LwpPOGUm21rl0cwoyYXAxw==,iv:+7J1nmeJfki0ZNzM+zKnk6MHHtpoIfl/QarI7+DW6T4=,tag:dDt29NEnLNBcsF0f0ipoWQ==,type:str]
    namespace: ENC[AES256_GCM,data:q1fHkiaA,iv:U7JNEUwnp4+UTA4VQeY80YaKx7ngigwLWm6mziU+bis=,tag:pPgiO2/iGpnut595nZQuLA==,type:str]
    labels:
        argocd.argoproj.io/secret-type: ENC[AES256_GCM,data:sOEIu2VnsXeNYw==,iv:ENFPGJq6y0MI3RTGXZFBOYFppITIRrAdWb44Sqg0ClI=,tag:TZl3AuBfpTJH4OZgJ8KQcQ==,type:str]
stringData:
    url: ENC[AES256_GCM,data:Xll6ioDr3PwVuAbgMQshloqYB4HycRJhWqu0qKaaSniP9BBANCHD/U8iH39PPF+O,iv:hTGp5bT8a+hgqOvvlstV/YQEY9cTfhzJbIaZx+xWLYQ=,tag:oFPgZJCQGYPTwoFTxndszg==,type:str]
    sshPrivateKey: ENC[AES256_GCM,data:hM6W//KzAGxLFmEvbiF3D/HdBAwPiNNFPQ6ZUz83AMGrfkG9ZjyPrl/6WprJuVcuuyAc5ZvAV2os7l4zHMCU6ytevPguRtxOfky/aZclzotgxOaJo+7mCe6clfJEJOzKep0dN5I/eJT3SPCHkc/XuHAmAN6cczzMr/gq5g76mk9r2vm1Fz2i6fgGLUNIOstclLi2J8Nv1wa794T2S8Lb35L2WcRAg+3mVkPwUm9eYtWmfXmP8JlXqyYk5IMW32ISzAZl8QntukSCmVszCjE6dQdpz6mV0lqsUYPFL+7k1MfhJecIcj/uWe/R0TItNrDWVn1tMlstNuSPafGCuH7FMn7BCRqmRlEJaEtPAGHG4j5JDjK/VBNb4mOcWIx44EQLe/2W7QiLXFTXSFHo9azxHFRphalzEicRyiOdB3p1J+a/JKlf1pjCTQC6qr2VdW44nYo8itu8B2QAX8iLHHJ2kkeaqWT4oWDLi6AtDPFgaw2OzRs1bmmjYKE0gD1EhFQfezzd,iv:NSrk4R+juxp/c09jyuNCFtSc78uOF4Oi1oxfrhSSgvg=,tag:M5/ZjyuE4mMw/y+deZaqyA==,type:str]
    insecure: ENC[AES256_GCM,data:8M5lcg==,iv:q56sTwVyZz/7kcBzwMyaYbyxfnXm6WIYKD9eGP2Xnf4=,tag:5TMau99Wswy7Mna/tJJ3Xw==,type:str]
    enableLfs: ENC[AES256_GCM,data:wa0R3A==,iv:0RnCsR9PYTXSg6l63eKrd0SnamgmHc7XFwAk3zoHDyM=,tag:ZhmjW2ezKtbtNnnNuIjtRw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/test-project-373118/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2024-11-17T15:07:02Z"
          enc: CiQAdOGM+iSgR9iy7ifrPKJQ6bKLfH4bH/b99kD9iBRHBili+xMSSQBuGHVK4SoDndu204NaugaOtMGhEkVdfKgySW7+C8ZlDUN5kBidha8YF70WXJqUMAyBVc/QIsjQzTE04k96SG5a9wZen5+IzGo=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-17T15:07:02Z"
    mac: ENC[AES256_GCM,data:cTmm7+0nAbP1+AOeGWfLyMITotiQCMidXoC571eQ0EpyOBusuLnMvNub8tzbOLJrQjLn8HdyhS328w1LV5N0Dp+c6Q3n1ROZiKRR2nEIeePcJhFuibF2aAqCI3wPhmtO11fTqFBaov5KCyCqbIGcEJE3CDZdCD49nF5Miuf62wI=,iv:lQ4x9mGOUkndrfxZFoldY1Ipx34Xrz4nUplOLBFikA4=,tag:XG1GHrYm/BG6CSq0BIUzGQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
