apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-study-deployment
  namespace: welcome-study
  labels:
    app: welcome-study
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-study
  template:
    metadata:
      labels:
        app: welcome-study
    spec:
      serviceAccountName: welcome-study-sa
      containers:
      - name: welcome-study
        image: asia-northeast1-docker.pkg.dev/test-project-373118/my-repository/welcome-study-app:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: welcome-study-service
  namespace: welcome-study
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: welcome-study
