name: "publish"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - "app/**"
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
    paths:
      - "app/**"

defaults:
  run:
    working-directory: .

# env:

jobs:
  Bench:
    name: "Publish Job"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
