# ref:
#   - https://gihyo.jp/article/2024/10/good-practices-for-github-actions
#   - https://zenn.dev/tmknom/articles/github-cicd-book#faq

name: "release"

on:
  workflow_dispatch:
  push:
    tags: ['v*']

defaults:
  run:
    shell: bash
    working-directory: app

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

env:
  APP_ROOT: ./app
  PROJECT_ID: test-project-373118
  PROJECT_NUMBER: 593997455442
  REGION: asia-northeast1
  WORKLOAD_IDENTITY_POOL: my-github-pool
  WORKLOAD_IDENTITY_POOL_PROVIDER: my-github-pool-provider
  REPOSITORY_NAME: my-repository
  IMAGE_NAME: welcome-study-app

jobs:
  build:
    name: Build Image Job
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha

      - uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.WORKLOAD_IDENTITY_POOL }}/providers/${{ env.WORKLOAD_IDENTITY_POOL_PROVIDER }}

      - run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          file: ${{ env.APP_ROOT }}/Dockerfile
          context: ${{ env.APP_ROOT }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
